backend:
  name: github
  repo: fallinov/2025-sfa-donnee-vuetify-vitepress
  branch: main
  base_url: https://oauth.kode.ch
  auth_scope: repo
  site_domain: fallinov.github.io
  auth_endpoint: callback.php

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "docs"
    label: "Documentation"
    folder: "/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
